<?php

namespace Moshp\Monitoring;

use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * Class MoshpMonitoring
 * @package Moshp\Monitoring
 */
class MoshpMonitoring extends Plugin
{

    public function build(ContainerBuilder $container): void
    {
        parent::build($container);

        $apiKey = $container->getParameter('new_relic.api_key');

        if (empty($apiKey)) {
            throw new \InvalidArgumentException('Missing api key for NewRelic.');
        }

    }

    /**
     * TODO: Ask for the required api key
     *
     * @param InstallContext $installContext
     */
    public function install(InstallContext $installContext): void
    {
        parent::install($installContext); // TODO: Change the autogenerated stub
    }

}
